#!/usr/bin/env bash
set -euo pipefail

script_dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
rm -rf $script_dir/zig-out/zlib-ana

zig build

if [ ! -e $script_dir/zlib ]; then
    set -x
    git clone https://github.com/madler/zlib $script_dir/zlib
    set +x
fi

(cd $script_dir/zlib && git reset --hard HEAD)
(cd $script_dir/zlib && git clean -xffd)

set -x
export CC="gcc"
export CC="$script_dir/zig-out/bin/cc-header-analyzer $script_dir/zig-out/zlib-ana -- $CC"

(cd zlib && ./configure --prefix=$script_dir/zlib/install)
make -C $script_dir/zlib install
